# Generated by Django 6.0.3 on 2026-03-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traiteur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='traiteurs/'),
        ),
    ]
