# Generated by Django 6.0.3 on 2026-04-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0002_alter_traiteur_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traiteur',
            name='date_de_creation',
        ),
        migrations.AddField(
            model_name='traiteur',
            name='experience',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
